name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        java-version:
        - 17
        - 21
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up Java
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: "temurin"
        cache: "maven"
    - name: Test
      run: mvn -B --no-transfer-progress clean install